### ISSUE TITLE
Softwarebitmap post to web api

### ISSUE THREAD

**Issue by RawadBahsas** [UoA-eResearch/hololens_facial_recognition#13]
Hi,
I am currently working on something similar to this project, where I have live feed from hololens camera and I use windows sdk to detect faces and draw rectangles around the faces in the 3d view. whenever I discover a face, I need to send its frame to an API to do face recognition the same way you do. what am facing is the byre array that am getting from the capture element is a Softwarebitmap, and my API is an ASP.NET web API. I receive the post request and I get the binary data, but I can't manage to convert it to a Bitmap to be used in my face recognition library. do you have any idea how to do so.?

**Comment by neon-ninja** [comment]
Hi,

Your question isn't really related to this project, so this issue tracker isn't really the best place for it. StackOverflow would be a better place to ask such a question, and you wouldn't be the first to ask it, for sure. You should be able to reconstruct the SoftwareBitmap on the receiving end, in your ASP.NET application (https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.copyfrombuffer#Windows_Graphics_Imaging_SoftwareBitmap_CopyFromBuffer_Windows_Storage_Streams_IBuffer_). You'll need to instantiate the bitmap with the appropriate pixel format, width and height first, then copy the binary into it. So the code would look something like

```c#
var bitmap = new SoftwareBitmap(BitmapPixelFormat.Nv12, width, height);
bitmap.CopyFromBuffer(bytes);
```
