### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by Xwil** [UoA-eResearch/hololens_facial_recognition#3]
I built it in Unity 5.5.0f3 , some errors happened.
1. in GazeGestureManager.cs line 45.
`captureObject.StartPhotoModeAsync(c, false ,OnPhotoModeStarted);`
it should be `captureObject.StartPhotoModeAsync(c,OnPhotoModeStarted);
2.I think you should add some guide in Readme.md,such as user should put config.cfg under Assets folder.

anyway,this project helps me a lot, thank you very much.(sorry,my english is so bad).

**Comment by geziefer** [comment]
1) is confirmed, should be added to the current source for others to not stumble upon this again
2) config in root folder worked for me with my own keys

**Comment by anaik12** [comment]
I am trying to interface with https://hub.docker.com/r/uoacer/openface-mass-compare/ for individual recognition and running into issues. I have created the docker container and have the instance up and running. However, when I air tap on face, even though its a face in the group, I dont see anything returned by recogString. Any idea why? Do I need to write additional lines of code? specifying the url and such?

**Comment by neon-ninja** [comment]
@anaik12 yes, you must configure the location of your openface server in your config.cfg. See https://github.com/UoA-eResearch/hololens_facial_recognition/blob/master/config.cfg.example

**Comment by anaik12** [comment]
I did with no luck. However, Should I rebuild the solution in Unity after
making the changes?

Also, I have the docker running fine. Here is the output of the test run -

root@chihiro:/home/anaik3# time curl localhost:8000 --data-binary
@Ashwi.jpg -vv
* Rebuilt URL to: localhost:8000/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 282026
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Server: gunicorn/19.7.1
< Date: Mon, 24 Apr 2017 23:54:53 GMT
< Connection: close
< Content-Length: 67
< Content-Type: application/json
<
* Closing connection 0
{"confidence": 0.95900479876891043, "data": null, "uid": "Ashwini"}
real    0m5.146s
user    0m0.004s
sys     0m0.000s
root@chihiro:/home/anaik3#

Thanks and Regards,
Ashwini Naik

**Comment by neon-ninja** [comment]
As I state in https://github.com/UoA-eResearch/hololens_facial_recognition/blob/master/README.md you must copy the example config file to a file called config.cfg

**Comment by neon-ninja** [comment]
And yes, you'll need to rebuild/redeploy after editing the config file

**Comment by anaik12** [comment]
Hi Nick,

I was able to get the docker to work fine. However, now I am now stuck
getting the additional data. I have created the additional data.json file
and the contents of it are as seen below.

*******************************************************************
root@chihiro:/# cd /root/data
root@chihiro:~/data# ls
data.json  data.pickle  images
root@chihiro:~/data# cat data.json
{
        "data": {
                "fullName": "Ashwini",
                "positions": [{
                        "position": "Research Assistant"
                }]
        }
}root@chihiro:~/data#

***********************************************************************

However, when I try to compare my data field still returns a null as seen
below.

***********************************************************************
< Content-Type: application/json
<
* Closing connection 0
{"confidence": 0.95900479876891043, "data": null, "uid": "Ashwini"}
real    0m4.758s
user    0m0.004s
sys     0m0.000s
root@chihiro:/home/anaik3#
************************************************************************

Is there something I am doing wrong. Any suggestions? I have checked
/var/log and it was of no help. Tried multiple restart of the docker
instance with no luck.

Thanks and Regards,
Ashwini Naik

**Comment by neon-ninja** [comment]
Restructure your data.json like this

```
{
        "Ashwini": {
                "fullName": "Ashwini",
                "positions": [{
                        "position": "Research Assistant"
                }]
        }
}
```

There will be nothing in /var/log, to view the logs use the command `docker logs -f omc`

**Comment by anaik12** [comment]
Got it! Thanks so much!

******************************************
< Content-Type: application/json
<
* Closing connection 0
{"confidence": 0.95900479876891043, "data": {"positions": [{"position":
"Research Assistant"}], "fullName": "Ashwini"}, "uid": "Ashwini"}
real    0m4.948s
user    0m0.004s
sys     0m0.000s
anaik3@chihiro:~$
*******************************************

Also, just wanted to let you know, this is for a class project we are
working on. We will be mentioning you in the credits section. It is not
complete yet. Will let you know once done.

Thanks and Regards,
Ashwini Naik
