### ISSUE TITLE
Unable to get the project to work

### ISSUE THREAD

**Issue by anaik12** [UoA-eResearch/hololens_facial_recognition#7]
Hi neon_ninja,

I am coming across multiple issues trying to run this. Not sure what I am doing wrong. 

When I am running using HoloLens version of Unity 5.4.0.f3. When I run it does say loaded settings from config.cfg where in I have populated my API keys. However, when I run in Unity all it does is gives me a cropped image of my example.jpg. Also on my Unity console it gives me

![image](https://cloud.githubusercontent.com/assets/19904581/24119571/baf3685a-0d7f-11e7-8083-d194bfc65b79.png)
![img_20170320_151747](https://cloud.githubusercontent.com/assets/19904581/24119987/0bab08f6-0d81-11e7-9134-d2ffeb24b395.jpg)

Also when I load the solution into VS2015, I am unable to explore the Configuration properties where I could change my target device. Any help on this would be greatly appreciated.

**Comment by neon-ninja** [comment]
Hololens Unity projects do not support being run from Unity itself. You will need to build the project and then deploy it to a hololens. See https://developer.microsoft.com/en-us/windows/holographic/holograms_100 for instructions on how to do that. This article also includes instuctions on how to configure VS2015 for Release x86

**Comment by anaik12** [comment]
Thanks Nick!

I will check it out!

Regards,
Ashwini Naik

**Comment by anaik12** [comment]
Nick!!! I got it working!

Thanks a ton! :)

Regards,
Ashwini Naik
